# Generated by Django 6.0.6 on 2026-07-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_identityverification_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='temp_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='security',
            name='temp_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
