# Generated by Django 6.0.7 on 2026-07-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_user_password_reset_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biller',
            name='bill_type',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('internet', 'Internet'), ('phone', 'Phone'), ('tv', 'TV / Cable'), ('insurance', 'Insurance'), ('tax', 'Tax'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
