# Generated by Django 6.0.7 on 2026-07-25 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_biller_bill_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biller',
            name='bill_type',
        ),
    ]
