# Generated by Django 6.0.7 on 2026-07-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_remove_biller_bill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('bill_payment', 'Bill Payment'), ('topup', 'Top Up'), ('withdrawal', 'Withdrawal'), ('security', 'Security'), ('kyc', 'KYC'), ('wallet', 'Wallet'), ('system', 'System')], default='system', max_length=50),
        ),
    ]
