# Generated by Django 6.0.7 on 2026-07-25 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='biller',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biller_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
