# Generated by Kilo - Address hierarchy models for Cambodia

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_bakongpayment_bakong_md5'),
    ]

    operations = [
        # Create Province model
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_other', models.CharField(blank=True, help_text='English name or alternative', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provinces_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        # Create District model
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_other', models.CharField(blank=True, help_text='English name or alternative', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts_created', to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='wallet.province')),
            ],
            options={
                'ordering': ['code'],
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        # Create Commune model
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_other', models.CharField(blank=True, help_text='English name or alternative', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communes_created', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='wallet.district')),
            ],
            options={
                'ordering': ['code'],
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
            },
        ),
        # Create Village model
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_other', models.CharField(blank=True, help_text='English name or alternative', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villages_created', to=settings.AUTH_USER_MODEL)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='wallet.commune')),
            ],
            options={
                'ordering': ['code'],
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
            },
        ),
        # Add village field to User
        migrations.AddField(
            model_name='user',
            name='village',
            field=models.ForeignKey(blank=True, help_text='Current residence village', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='wallet.village'),
        ),
        migrations.AddField(
            model_name='user',
            name='street_address',
            field=models.CharField(blank=True, help_text='House number, street, building', max_length=255, null=True),
        ),
        # Add village and address_detail to IdentityVerification
        migrations.AddField(
            model_name='identityverification',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_residents', to='wallet.village'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='address_detail',
            field=models.CharField(blank=True, help_text='House number, street, additional details', max_length=255, null=True),
        ),
        # Alter address field in IdentityVerification to add help text
        migrations.AlterField(
            model_name='identityverification',
            name='address',
            field=models.TextField(blank=True, help_text='Legacy free-text address (auto-generated from village if empty)', null=True),
        ),
    ]
