"""
Django settings for e_wallet_project project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import dj_database_url
import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Bunli address service. Keep the bearer token in .env, never in source code.
BUNLI_ADDRESS_API_URL = (
    os.getenv('BUNLI_ADDRESS_API_URL')
    or os.getenv('USP_ADDRESS_BASE_URL')
    or 'https://usp.bunli-it.site/api/v1'
).rstrip('/')
BUNLI_ADDRESS_API_TOKEN = (
    os.getenv('BUNLI_ADDRESS_API_TOKEN')
    or os.getenv('USP_ADDRESS_API_TOKEN', '')
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p4b0qb%_(_=8t72h4u^n#pncosyu0x89rx21!p&%rx8brjntwl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# HTTPS development tunnel used to test the app from mobile devices.
CSRF_TRUSTED_ORIGINS = [
    'https://sector-ritzy-degrease.ngrok-free.dev',
    'http://127.0.0.1',
    'http://localhost',
]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF Cookie settings
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False  # Must be False for JavaScript to access it
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False  # Use cookie-based CSRF tokens
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'wallet',
]

AUTH_USER_MODEL = 'wallet.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'wallet.authentication.CookieJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'wallet.authentication.JWTSessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'e_wallet_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'wallet.context_processors.notification_counts',
            ],
        },
    },
]

WSGI_APPLICATION = 'e_wallet_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Phnom_Penh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ── Auth redirect settings ─────────────────────────────────────────
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# ── Resend Email Configuration ───────────────────────────────────────
# Get your API key from: https://resend.com/api-keys
RESEND_API_KEY = os.getenv('RESEND_API_KEY', '')
RESEND_FROM_EMAIL = os.getenv('RESEND_FROM_EMAIL', 'onboarding@resend.dev')

# Frontend URL for password reset links
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# ── Default primary key field type ────────────────────────────────
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Cloudinary Configuration ──────────────────────────────────────
import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config(
    cloud_name=os.getenv('CLOUDINARY_KEY_NAME', ''),
    api_key=os.getenv('CLOUDINARY_API_KEY', ''),
    api_secret=os.getenv('CLOUDINARY_API_SECRET', ''),
    secure=True
)

# ── Bakong Payment Configuration ───────────────────────────────────
BAKONG_TOKEN = os.getenv('BAKONG_TOKEN', '')
BAKONG_ACCOUNT_ID = os.getenv('BAKONG_ACCOUNT_ID', '')
BAKONG_MERCHANT_NAME = os.getenv('BAKONG_MERCHANT_NAME', '')
BAKONG_MERCHANT_CITY = os.getenv('BAKONG_MERCHANT_CITY', '')
# Bakong's production API base URL.  Set this to
# https://sit-api-bakong.nbc.gov.kh when using a SIT token.
BAKONG_API_URL = os.getenv('BAKONG_API_URL', 'https://api-bakong.nbc.gov.kh')

# ── Django Jazzmin Configuration ───────────────────────────────────
JAZZMIN_SETTINGS = {
    "site_title": "E-Wallet Admin",
    "site_header": "E-Wallet",
    "site_brand": "E-Wallet",
    "site_icon": "fas fa-wallet",
    "site_logo": None,
    "welcome_sign": "Welcome to E-Wallet Admin",
    "copyright": "E-Wallet Payment System",
    "search_model": ["wallet.User", "wallet.Transaction", "wallet.Wallet"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "API", "url": "/", "new_window": True},
    ],
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["wallet", "auth"],
    "custom_links": {
        "wallet": [{
            "name": "View Site",
            "url": "/",
            "icon": "fas fa-external-link-alt",
            "permissions": ["wallet.view_user"]
        }]
    },
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "wallet.User": "fas fa-user",
        "wallet.Wallet": "fas fa-wallet",
        "wallet.Transaction": "fas fa-exchange-alt",
        "wallet.Transfer": "fas fa-paper-plane",
        "wallet.Merchant": "fas fa-store",
        "wallet.Biller": "fas fa-file-invoice",
        "wallet.Notification": "fas fa-bell",
        "wallet.IdentityVerification": "fas fa-id-card",
        "wallet.Security": "fas fa-shield-alt",
        "wallet.TransactionLimit": "fas fa-sliders-h",
        "wallet.AuditLog": "fas fa-clipboard-list",
        "wallet.Topup": "fas fa-plus-circle",
        "wallet.Withdrawal": "fas fa-minus-circle",
        "wallet.BillPayment": "fas fa-file-invoice-dollar",
        "wallet.MerchantQR": "fas fa-qrcode",
        "wallet.BakongPayment": "fas fa-credit-card",
        "wallet.FraudDetection": "fas fa-user-secret",
        "wallet.Province": "fas fa-map-marker-alt",
        "wallet.District": "fas fa-map",
        "wallet.Commune": "fas fa-city",
        "wallet.Village": "fas fa-home",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False,
}
